### PR TITLE
Announce HHVM 4.158

### PR DESCRIPTION
**Pull request by Atry**

### CODE REVIEW

**Comment by AndrewDiMola** [comment]
Looks good. Do you think there's anything that needs to be updated in https://docs.hhvm.com/hack/traits-and-interfaces/using-a-trait?

**Comment by AndrewDiMola** [comment]
Probably just remove this section, right?

> _Remove support for the `elseif` keyword_

https://docs.hhvm.com/hack/statements/if#elseif-syntax

**Comment by Atry** [comment]
> Looks good. Do you think there's anything that needs to be updated for traits in the docs?
> 
> > _Remove support for trait precedence and trait alias from HHVM._
> 
> https://docs.hhvm.com/hack/traits-and-interfaces/using-a-trait

I think the current document did not mention trait precedence and trait alias. So I would not change the page.

**Comment by alexeyt** [comment]
Looks good. I don't see any mention of https://github.com/facebook/hhvm/commit/8c97ca321535a78eeb63d1f26e4ecc6456b1f8e2 ? Is that because the typechecker support is not ready yet? If so we should remember to announce this later when it becomes fully ready.

**Review by alexeyt — APPROVED** [review]

**Comment by Atry** [comment]
> Looks good. I don't see any mention of [facebook/hhvm@8c97ca3](https://github.com/facebook/hhvm/commit/8c97ca321535a78eeb63d1f26e4ecc6456b1f8e2) ? Is that because the typechecker support is not ready yet? If so we should remember to announce this later when it becomes fully ready.

I didn't mention it because it is an unstable feature.

**Pull request merged**
